### ISSUE TITLE
change of signature on event OnAfterTransportPostPrint table "BET AUT Sales Transport Data"

### ISSUE THREAD

**Issue by batakasa86** [BEIndustry/BEIndustryExtensions#10]
New signature is:
```
[IntegrationEvent(false, false)]
local procedure OnAfterTransportPostPrint(var ShippingDocumentSelection: Page "BET AUT Ship. Doc. Selection";lvRefNo: Code[8]; Preview: Boolean)
    begin
    end;
```

**Comment by ralf-escher** [comment]
https://dev.azure.com/BE-terna-Development/BC.BE-Industry/_workitems/edit/11107

**Comment by ralf-escher** [comment]
I suggest following code
ShippingDocumentSelection will be not checked at the end: no reference required
PostedSalesTransportData: is a RecordSet (more than one transport if this is a Porsche Time Slot process)

`
    [IntegrationEvent(false, false)]
    local procedure OnAfterTransportPostPrint(ShippingDocumentSelection: Page "BET AUT Ship. Doc. Selection"; var PostedSalesTransportData: Record "BET AUT Post. Sales Trans. D."; Preview: Boolean)
    begin
    end;
`
