### ISSUE TITLE
[Event Request] Codeunit 5140429 BET BEM LOG SMART Receipt - OnBeforeFindWarehouseActivityLineTake

### ISSUE THREAD

**Issue by rsambeterna** [BEIndustry/BEIndustryExtensions#12]
Codeunit 5140429 BET BEM LOG SMART Receipt - OnBeforeFindWarehouseActivityLineTake
 
    [IntegrationEvent(false, false)]
    local procedure OnBeforeFindWarehouseActivityLineTake(var WarehouseActivityLine: Record "Warehouse Activity Line")
    begin
    end;

     
Call for Function:

    local procedure PutAway()
    var
        WarehouseActivityLinePlace: Record "Warehouse Activity Line";
        WarehouseActivityLineTake: Record "Warehouse Activity Line";
        WarehouseEmployee: Record "Warehouse Employee";
        Counter: Integer;
        LocationCodeFilter: Text;
    begin
        [...]

        WarehouseActivityLineTake.SetRange("Activity Type", WarehouseActivityLineTake."activity type"::"Put-away");
        WarehouseActivityLineTake.SetRange("Action Type", WarehouseActivityLineTake."action type"::Take);
        WarehouseActivityLineTake.SetFilter("Location Code", LocationCodeFilter);
        OnBeforefindWarehouseActivityLineTake(WarehouseActivityLineTake);
        if not WarehouseActivityLineTake.FindSet() then
            exit;

        Counter := 0;
        [...]
    
    end;

**Comment by BE-Ouaali** [comment]
Will be added with IND29.0.10.0 and IND30.0.3.0.
