### ISSUE TITLE
Codeunit 5140432 BET BEM LOG SMART Shipment - PickCreatePickListOnBeforeFindSet

### ISSUE THREAD

**Issue by rsambeterna** [BEIndustry/BEIndustryExtensions#13]
Please add a new integration event PickCreatePickListOnBeforeFindSet in Codeunit 5140432 BET BEM LOG SMART Shipment.

    [IntegrationEvent(false, false)]
    local procedure PickCreatePickListOnBeforeFindSet(var WarehouseActivityLinePlace: Record "Warehouse Activity Line")
    begin
    end;

Call for function:

    local procedure PickCreatePickList()
    var
        WarehouseActivityLinePlace: Record "Warehouse Activity Line";
        WarehouseActivityLineTake: Record "Warehouse Activity Line";
        WarehouseEmployee: Record "Warehouse Employee";
        BinCodeFilter: Code[20];
        DocumentNoFilter: Code[20];
        ItemFilter: Code[20];
        Counter: Integer;
        LocationCodeFilter: Text;
    begin
       ...
        WarehouseActivityLinePlace.SetRange("Activity Type", WarehouseActivityLinePlace."activity type"::Pick);
        WarehouseActivityLinePlace.SetRange("Source Document", WarehouseActivityLinePlace."source document"::"Sales Order");
        WarehouseActivityLinePlace.SetRange("Action Type", WarehouseActivityLinePlace."action type"::Place);
        WarehouseActivityLinePlace.SetFilter("Location Code", LocationCodeFilter);
        if ItemFilter <> '' then
            WarehouseActivityLinePlace.SetRange("Item No.", ItemFilter);
        if BinCodeFilter <> '' then
            WarehouseActivityLinePlace.SetRange("Bin Code", BinCodeFilter);
        if DocumentNoFilter <> '' then
            WarehouseActivityLinePlace.SetRange("No.", DocumentNoFilter);

        PickCreatePickListOnBeforeFindSet(WarehouseActivityLinePlace);
        if not WarehouseActivityLinePlace.FindSet() then
            exit;

        Counter := 0;

**Comment by beterna-cstuber** [comment]
Will be added with IND29.0.5.13, IND29.0.10.0 and IND30.0.4.0.
