### ISSUE TITLE
[Event Request] Codeunit 5140429 BET BEM LOG SMART Receipt - OnAfterReceiptMenu

### ISSUE THREAD

**Issue by rsambeterna** [BEIndustry/BEIndustryExtensions#14]
Please add a new integration event OnAfterReceiptMenu in Codeunit 5140429 BET BEM LOG SMART Receipt and provide a hotfix for ALPINA

    [IntegrationEvent(false, false)]
    local procedure OnAfterReceiptMenu(var IT_BEM: Record "BET BEM Interface" temporary)
    begin
    end;

Call for Function

    local procedure ReceiptMenu()
    begin
        IF_BEM.CreateScreen(IT_BEM, TC_BEM_LOG.IDSmartReceipt(), '', TC_BEM_LOG.CaptionWarehouseReceipt());
        IF_BEM.AddTile(IT_BEM, TC_BEM_LOG.FunctionIDSmartReceiptOverview(), TC_BEM_LOG.ActionSmartReceiptOverview(), TC_BEM_LOG.CaptionWarehouseReceipts(), TC_BEM.IconBusinessCreditCardCheck(), TC_BEM.GlobalColorFunction());
        IF_BEM.AddTile(IT_BEM, TC_BEM_LOG.FunctionIDSmartPutAway(), TC_BEM_LOG.ActionSmartPutAway(), TC_BEM_LOG.CaptionPutAways(), TC_BEM.IconShippingdeliveryBoxMoveAllDirection(), TC_BEM.GlobalColorFunction());
        OnAfterReceiptMenu(IT_BEM);
    end;

**Comment by ralf-escher** [comment]
https://dev.azure.com/BE-terna-Development/BC.BE-Industry/_workitems/edit/15816
