### ISSUE TITLE
[Event Request] Table 5042673 BET AUT Sales Transport Data - OnAfterTransportPostPrint

### ISSUE THREAD

**Issue by batakasa86** [BEIndustry/BEIndustryExtensions#6]
Please add a new integration event OnAfterTransportPostPrint in table 5042673 

    [IntegrationEvent(false, false)]
    local procedure OnAfterTransportPostPrint(BETAUTPostSalesTransD: "Record "BET AUT Post. Sales Trans. D."; ReferenceNo:     Code[8]; lvPreview: Boolean)
    begin
    end;

Call for function (fun: TransportPostPrint at end of function ):

    if ShippingDocumentSelection.GetShippingEDI() then begin
            PostedSalesTransportData.Get(ReferenceNo);
            PostedSalesTransportData.CreateShippingEDI();
        end;

        OnAfterTransportPostPrint(PostedSalesTransportData,ReferenceNo,lvPreview);

        exit(true);
    end;

**Comment by ralf-escher** [comment]
https://dev.azure.com/NAV-Industry/BE-Industry/_workitems/edit/3113

**Comment by ralf-escher** [comment]
will be added with Industry 29.0.2.0
ReferenceNo is not required, you can use `PostedSalesTransportData."Shipment Load Reference No."`
`PostedSalesTransportData `added by Reference (could be multiple for Porsche Time Slot process)

```
[IntegrationEvent(false, false)]
local procedure OnAfterTransportPostPrint(var PostedSalesTransportData: Record "BET AUT Post. Sales Trans. D."; Preview: Boolean)
begin
end;
```
