### ISSUE TITLE
[Event Request] table 5042676 "BET AUT Post. Sales Trans. D." - OnAfterPrint

### ISSUE THREAD

**Issue by batakasa86** [BEIndustry/BEIndustryExtensions#9]
Please add a new integration event OnAfterPrint Table 5042676 "BET AUT Post. Sales Trans. D."

```
[IntegrationEvent(false, false)]
local procedure OnAfterPrint(var ShipDocSelect: Page "BET AUT Ship. Doc. Selection"; var PostedSalesTransportData: Record "BET AUT Post. Sales Trans. D."; Preview: Boolean)
    begin
    end;
```

Call for function:

```
        if lpShipDocSelect.GetMaterialTag() then
            AutomotiveLabelFunctions.PrintLoadingEquipment(PostedSalesTransportData.RecordId, lvPreview);

    until PostedSalesTransportData.Next() = 0;

    if lpShipDocSelect.GetDeliveryEDI() then
        CreateDeliveryEDI();

    if lpShipDocSelect.GetShippingEDI() then
        CreateShippingEDI();

     OnAfterPrint(lpShipDocSelect);

end;
```

**Comment by batakasa86** [comment]
Hi,

sorry for this, but need one more variable (its Preview).
(I edit last comment)

BR,
Slobodan

**Comment by ralf-escher** [comment]
Please check the code:
`
    [IntegrationEvent(false, false)]
    local procedure OnAfterPrint(ShippingDocumentSelection: Page "BET AUT Ship. Doc. Selection"; var PostedSalesTransportData: Record "BET AUT Post. Sales Trans. D."; Preview: Boolean)
    begin
    end;`
